// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer, urlSearchParamsBodySerializer } from './client';
import type { StartLoadingAdminLoadStartPostData, StartLoadingAdminLoadStartPostResponses, StartTeamAlignementAdminAutoteamStartPostData, StartTeamAlignementAdminAutoteamStartPostResponses, GetAdminUserAdminUserGetData, GetAdminUserAdminUserGetResponses, GetOperationAdminOperationGetData, GetOperationAdminOperationGetResponses, GetTasksAdminTasksGetData, GetTasksAdminTasksGetResponses, GetTasksAdminTasksGetErrors, UploadMatchesCsvAdminMatchesUploadPostData, UploadMatchesCsvAdminMatchesUploadPostResponses, UploadMatchesCsvAdminMatchesUploadPostErrors, GetPlayersPlayersGetData, GetPlayersPlayersGetResponses, GetPlayerPlayersIdPlayerIdGetData, GetPlayerPlayersIdPlayerIdGetResponses, GetPlayerPlayersIdPlayerIdGetErrors, GetPlayerStatsPlayersStatsIdPlayerIdGetData, GetPlayerStatsPlayersStatsIdPlayerIdGetResponses, GetPlayerStatsPlayersStatsIdPlayerIdGetErrors, GetLatestPlayerStatsPlayersLatestGetData, GetLatestPlayerStatsPlayersLatestGetResponses, LoadMyteamLoadPostData, LoadMyteamLoadPostResponses, LoadMyteamLoadPostErrors, RegisterForAutolinupMyteamAutolineupRegisterPostData, RegisterForAutolinupMyteamAutolineupRegisterPostResponses, RegisterForAutolinupMyteamAutolineupRegisterPostErrors, UnregisterForAutolinupMyteamAutolineupUnregisterPostData, UnregisterForAutolinupMyteamAutolineupUnregisterPostResponses, UnregisterForAutolinupMyteamAutolineupUnregisterPostErrors, TeamValueEvolutionMyteamTeamValueEvolutionPostData, TeamValueEvolutionMyteamTeamValueEvolutionPostResponses, TeamValueEvolutionMyteamTeamValueEvolutionPostErrors, PingServerPingGetData, PingServerPingGetResponses, LoginAdminLoginPostData, LoginAdminLoginPostResponses, LoginAdminLoginPostErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Start Loading
 */
export const startLoadingAdminLoadStartPost = <ThrowOnError extends boolean = false>(options?: Options<StartLoadingAdminLoadStartPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<StartLoadingAdminLoadStartPostResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/admin/load/start',
        ...options
    });
};

/**
 * Start Team Alignement
 */
export const startTeamAlignementAdminAutoteamStartPost = <ThrowOnError extends boolean = false>(options?: Options<StartTeamAlignementAdminAutoteamStartPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<StartTeamAlignementAdminAutoteamStartPostResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/admin/autoteam/start',
        ...options
    });
};

/**
 * Get Admin User
 */
export const getAdminUserAdminUserGet = <ThrowOnError extends boolean = false>(options?: Options<GetAdminUserAdminUserGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAdminUserAdminUserGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/admin/user',
        ...options
    });
};

/**
 * Get Operation
 */
export const getOperationAdminOperationGet = <ThrowOnError extends boolean = false>(options?: Options<GetOperationAdminOperationGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetOperationAdminOperationGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/admin/operation',
        ...options
    });
};

/**
 * Get Tasks
 * Get tasks with pagination, ordered by most recent first
 */
export const getTasksAdminTasksGet = <ThrowOnError extends boolean = false>(options?: Options<GetTasksAdminTasksGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTasksAdminTasksGetResponses, GetTasksAdminTasksGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/admin/tasks',
        ...options
    });
};

/**
 * Upload Matches Csv
 * Upload a CSV file containing match data.
 * The file should be in the format with columns for date, time, home team, away team, and match ID.
 * Existing matches (by ID) will be updated, new matches will be inserted.
 * Maximum file size: 5MB.
 */
export const uploadMatchesCsvAdminMatchesUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadMatchesCsvAdminMatchesUploadPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UploadMatchesCsvAdminMatchesUploadPostResponses, UploadMatchesCsvAdminMatchesUploadPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/admin/matches/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Get Players
 * Get all players of the current season
 */
export const getPlayersPlayersGet = <ThrowOnError extends boolean = false>(options?: Options<GetPlayersPlayersGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetPlayersPlayersGetResponses, unknown, ThrowOnError>({
        url: '/players/',
        ...options
    });
};

/**
 * Get Player
 * Get the data of one player
 */
export const getPlayerPlayersIdPlayerIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPlayerPlayersIdPlayerIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlayerPlayersIdPlayerIdGetResponses, GetPlayerPlayersIdPlayerIdGetErrors, ThrowOnError>({
        url: '/players/id/{player_id}',
        ...options
    });
};

/**
 * Get Player Stats
 */
export const getPlayerStatsPlayersStatsIdPlayerIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPlayerStatsPlayersStatsIdPlayerIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPlayerStatsPlayersStatsIdPlayerIdGetResponses, GetPlayerStatsPlayersStatsIdPlayerIdGetErrors, ThrowOnError>({
        url: '/players/stats/id/{player_id}',
        ...options
    });
};

/**
 * Get Latest Player Stats
 */
export const getLatestPlayerStatsPlayersLatestGet = <ThrowOnError extends boolean = false>(options?: Options<GetLatestPlayerStatsPlayersLatestGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetLatestPlayerStatsPlayersLatestGetResponses, unknown, ThrowOnError>({
        url: '/players/latest/',
        ...options
    });
};

/**
 * Load
 */
export const loadMyteamLoadPost = <ThrowOnError extends boolean = false>(options: Options<LoadMyteamLoadPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoadMyteamLoadPostResponses, LoadMyteamLoadPostErrors, ThrowOnError>({
        url: '/myteam/load',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Register For Autolinup
 */
export const registerForAutolinupMyteamAutolineupRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterForAutolinupMyteamAutolineupRegisterPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterForAutolinupMyteamAutolineupRegisterPostResponses, RegisterForAutolinupMyteamAutolineupRegisterPostErrors, ThrowOnError>({
        url: '/myteam/autolineup/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Unregister For Autolinup
 */
export const unregisterForAutolinupMyteamAutolineupUnregisterPost = <ThrowOnError extends boolean = false>(options: Options<UnregisterForAutolinupMyteamAutolineupUnregisterPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UnregisterForAutolinupMyteamAutolineupUnregisterPostResponses, UnregisterForAutolinupMyteamAutolineupUnregisterPostErrors, ThrowOnError>({
        url: '/myteam/autolineup/unregister',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Team Value Evolution
 */
export const teamValueEvolutionMyteamTeamValueEvolutionPost = <ThrowOnError extends boolean = false>(options: Options<TeamValueEvolutionMyteamTeamValueEvolutionPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<TeamValueEvolutionMyteamTeamValueEvolutionPostResponses, TeamValueEvolutionMyteamTeamValueEvolutionPostErrors, ThrowOnError>({
        url: '/myteam/team_value_evolution',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Ping Server
 */
export const pingServerPingGet = <ThrowOnError extends boolean = false>(options?: Options<PingServerPingGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<PingServerPingGetResponses, unknown, ThrowOnError>({
        url: '/ping',
        ...options
    });
};

/**
 * Login
 */
export const loginAdminLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginAdminLoginPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginAdminLoginPostResponses, LoginAdminLoginPostErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/admin/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};